spring:
  application:
    name: schedule-task
  profiles:
    active: dev
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    enabled: true
    encoding: UTF-8
    mode: HTML

server:
  port: 9527
  servlet:
    context-path: /job

mybatis-plus:
  type-aliases-package: com.hong.task.domain
  mapper-locations: classpath:mapper/*.xml
  global-config:
    id-type: 2
    field-strategy: 2
    db-column-underline: true
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
