spring:
  application:
    name: schedule-task
  profiles:
    active: dev

server:
  port: 9527
  servlet:
    context-path: /job

mybatis-plus:
  type-aliases-package: com.hong.task.domain
  mapper-locations: classpath:mapper/*.xml
  global-config:
    id-type: 2
    field-strategy: 2
    db-column-underline: true
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
